### ISSUE TITLE
Let's move this to the openedx organization?

### ISSUE THREAD

**Issue by nedbat** [openedx/openedx-i18n#1]
The organization is brand-new, but this would be perfect there: https://github.com/openedx/

**Comment by regisb** [comment]
Agreed! It makes sense to keep this under the umbrella of the openedx org. There are no star/issue/pr to transfer, but I'd rather avoid breaking the openedx docker image that [rely on this repo](https://github.com/regisb/openedx-docker/blob/master/openedx/Dockerfile#L59), if possible. So I'm going to ask a transfer to the openedx organization.

Will I have commit rights to this repo?

EDIT: in order to make the transfer, I need to have the rights to create a repo in the openedx organization. Is that possible, even temporarily? If not then I'll just delete the repo once you forked it.

**Comment by nedbat** [comment]
I've invited you to the openedx org

**Comment by regisb** [comment]
Done!
