### ISSUE TITLE
Farsi 

### ISSUE THREAD

**Issue by bahramiramazan** [openedx/openedx-i18n#11]
Plz add Farsi /persian to the supported languages .

**Comment by regisb** [comment]
Hi @bahramiRamazan! It's no trouble at all to add an item to the list of languages processed in this project. However, I see that persian has just shy of 50% of translated strings (49.2%) on Transifex: https://www.transifex.com/open-edx/
Would you be willing to contribute to Transifex so that Persian gets past the 50% line?

**Comment by bahramiramazan** [comment]
How can I contribute ?

**Comment by regisb** [comment]
All Open edX translations are hosted on Transifex. Please read the following document to get started: https://docs.transifex.com/getting-started-1/translators
Then, join the "open-edx" team and start translating strings in the "edx-platform" project.

**Comment by regisb** [comment]
Closed by #16
